CREATE TABLE test_results (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  personality_type text,
  top_careers text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Turn on row level security
alter table test_results enable row level security;

-- Create policies
create policy "Users can insert their own test results."
  on test_results for insert
  with check ( auth.uid() = user_id );

create policy "Users can view their own test results."
  on test_results for select
  using ( auth.uid() = user_id );
